version: '3'

services:
   wordpress:
     container_name: ${PROJECT_NAME}
     depends_on:
       - db
     image: wordpress:${WORDPRESS_VERSION}
     ports:
       - "8081:80"
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: ${DB_USER}
       WORDPRESS_DB_PASSWORD: ${DB_PASS}
       WORDPRESS_DB_NAME: ${DB_NAME}
     volumes:
      - ${PROJECT_PATH}:/var/www/html
      - ../php/php.ini:/usr/local/etc/php/conf.d/php.ini

   db:
     container_name: ${PROJECT_NAME}_mysql
     image: mysql:${MYSQL_VERSION}
     volumes:
       - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: ${DB_PASS}
       MYSQL_DATABASE: ${DB_NAME}
       MYSQL_USER: ${DB_USER}
       MYSQL_PASSWORD: ${DB_PASS}
       TZ: ${TZ}
     ports:
       - 4306:3306

volumes:
  db_data: 
